server:
  port: 8080
management:
  server:
    port: 8088 #管理端口调整成8088
  endpoints:
    web:
      base-path: '/monitor' #actuator的访问路径
      exposure:
        include: '*' #开放所有页面节点  默认只开启了health、info两个节点
    shutdown:
      enabled: true
  endpoint:
    health:
      show-details: always #显示健康具体信息  默认不会显示详细信息

info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
spring:
  security:
    user:
      name: admin
      password: 123456
      roles: admin
